### ISSUE TITLE
Replace demo with Asciidoctor-based sample article

### ISSUE THREAD

**Issue by dohliam** [darshandsoni/asciidoctor-skins#29]
The current demo page is based on the html5-test-page project. It does a good job of demonstrating most of the elements included in HTML5, but it is missing many Asciidoctor-specific features such as admonitions. To give a better sense of how the themes look when applied to `.adoc` files, the demo should be replaced with an Asciidoctor-based sample article.

**Comment by darshandsoni** [comment]
Closed thanks to this [PR](https://github.com/darshandsoni/asciidoctor-skins/pull/30) being merged
