### ISSUE TITLE
Requesting 'classic' theme emulating the look of asciidoc

### ISSUE THREAD

**Issue by eric-s-raymond** [darshandsoni/asciidoctor-skins#35]
It would be desirable to be able to migrate documentation from asciidoc to asciidoctor while preserving the styling, and then make separate consideration of whether to change it.

Can we please have an "asciidoc" or "classic"  theme that emulates, as possible, the original asciidoc style?

**Comment by dohliam** [comment]
@eric-s-raymond Thanks for the suggestion! The "classic" Asciidoc stylesheet appears to be located [here](https://github.com/asciidoc/asciidoc/blob/master/stylesheets/asciidoc.css). Loading that CSS into the Asciidoctor Skins preview page indeed produces the expected result (see screenshot below).

[Asciidoc](https://github.com/asciidoc/asciidoc/) is released as GPLv2 so it should be possible to include the stylesheet here with a link to the license. I can put together a PR for this shortly.

![image](https://user-images.githubusercontent.com/9295750/79394147-a8c49c00-7f2b-11ea-9ebc-ee58207d677d.png)

**Comment by eric-s-raymond** [comment]
Thanks for the rapid response!
