### ISSUE TITLE
Do not link against the stylesheet on asciidoctor.org

### ISSUE THREAD

**Issue by mojavelinux** [darshandsoni/asciidoctor-skins#37]
The stylesheet on asciidoctor.org is not the official default stylesheet for Asciidoctor. Please don't link against it. That stylesheet has extra styles that are required for the website to function. It's also not kept in sync with the stylesheet shipped with Asciidoctor and may move when the website is redesigned.

Instead, you can use the following URL to retrieve the default stylesheet for the latest release directly from the GitHub repository:

https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor@v2.0.10/data/stylesheets/asciidoctor-default.css

If you want to link against the development version instead, you can use this URL:

https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor@master/data/stylesheets/asciidoctor-default.css

**Comment by darshandsoni** [comment]
Sorry for the late response on these. AFK for a while. Good to know this and sorting it out!
