### ISSUE TITLE
asciidoctor.css Unexpected missing generic font family in stylesheet

### ISSUE THREAD

**Issue by bfitzpat** [darshandsoni/asciidoctor-skins#39]
We are using the asciidoctor.css stylesheet we found in your project to help with the vscode-didact project (https://github.com/redhat-developer/vscode-didact) and while working through some issues reported by SonarCloud, I received the error: `Unexpected missing generic font family`

on this line: https://github.com/darshandsoni/asciidoctor-skins/blob/71ce8dcd401600985dcce7b78d5b5d8b20a0a52d/css/asciidoctor.css#L234

```
.verseblock pre{font-family:"Open Sans","DejaVu Sans",sans;font-size:1.15rem;color:rgba(0,0,0,.85);font-weight:300;text-rendering:optimizeLegibility}
```

Here's a bit more about the issue: https://rules.sonarsource.com/css/RSPEC-4649

It appears that 'sans' is not a globally accepted font name, but 'sans-serif' is.

**Comment by dohliam** [comment]
@bfitzpat You might want to take a look at #37, specifically the recommendation to **not** use the current asciidoctor.css stylesheet in this repo (which we are in the process of replacing as per the instructions below):

> use the following URL to retrieve the default stylesheet for the latest release directly from the GitHub repository:
>
> https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor@v2.0.10/data/stylesheets/asciidoctor-default.css
> 
> If you want to link against the development version instead, you can use this URL:
>
> https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor@master/data/stylesheets/asciidoctor-default.css

I would suggest replacing the stylesheet you are currently using with one of the links above and seeing if that resolves your issue.

**Comment by bfitzpat** [comment]
Thanks @dohliam  -- I'll take a look!

**Comment by bfitzpat** [comment]
Closing this issue as an unneeded fix. Thanks @dohliam !
