### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by dohliam** [darshandsoni/asciidoctor-skins#6]
I noticed the error below on loading the skins:

```
Failed to load resource: the server responded with a status of 404 (Not Found) => http://darshandsoni.com/asciidoctor-skins/css/css/asciidoctor.css
```

It seems that this is occurring because of [this line](https://github.com/darshandsoni/asciidoctor-skins/blob/c65e3b608b3bd6b795b1e140453d3655836b1b0b/css/plain.css#L4) that tries to import asciidoctor.css from `css/asciidoctor.css`, which of course doesn't exist now since the skins themselves are located in the css directory.

I'll see if I can submit a PR to fix this.

**Comment by darshandsoni** [comment]
It's funny how that's not showing up on my end... and asciidoctor seems to work as intended... despite the fact that you're obviously right and that path should invalidate!

**Comment by darshandsoni** [comment]
I shall merge the PR anyway, because it's the right thing to do.

**Comment by dohliam** [comment]
For future reference, I think it was still working anyway even with the wrong path because we are actually loading the default stylesheet _twice_ (once in `index.html`, and again in each custom skin).

**Comment by darshandsoni** [comment]
Ahh that explains it! Thanks for picking that up. There's always a simple, logical explanation at the end of all of weird bugs.
